<h1>Add a new Jeu</h1>
<form method="jeu" action="?page=adminjeu&action=create">
<div class="mb-3">
  <label for="nom" class="form-label">nom</label>
  <input type="text" class="form-control" name="nom" id="nom" placeholder="Add a nom">
</div>
<div class="mb-3">
  <label for="description" class="form-label">Description</label>
  <textarea maxlength="255" class="form-control" name="description" id="description" placeholder="Add a description">
</textarea>
</div>
<div class="mb-3">
  <label for="image" class="form-label">Image</label>
  <input type="text" class="form-control" name="image"  id="image" placeholder="Add an url">
</div>
<div class="mb-3">
  <input type="submit" class="btn btn-success" value="Add a new jeu Now !">
</div>
</form>