<h1>Gallery</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio vel exercitationem quasi, nemo voluptatem eligendi neque, repellendus unde iusto explicabo numquam voluptatum illum expedita ab quia, quibusdam doloribus dolorum. Nulla.</p>
<section id="galerie" class="row">
    <?php
    foreach ($jeux as $game) :
    ?>
        <article class="col-12 col-sm-6 col-md-4 mb-3">
            <div class="card">
                <a href="?page=jeudetail&id=<?= $game['id'] ?>">
                    <img src="<?= $game['image'] ?>" class="card-img-top" alt="<?= $game['nom'] ?>">
                </a>
                <div class="card-body">
                    <h5 class="card-title"><?= $game['nom'] ?></h5>
                    <p class="card-text"><?= substr($game['description'], 0, 60) ?>...</p>
                    <div class="container-fluid info">
                    <p class="row">
                    <span class="col-6"><small>Author:<strong>&nbsp;<?= $game['prenom'] ?>&nbsp;<?= $game['nom'] ?></strong></small></span>
                    <span class="col-6 text-end"><small>Date:<strong>&nbsp;<?= $game['created_at'] ?></strong></small></span>
                    </p>
                    </div>
                    <a href="?page=jeudetail&id=<?= $game['id'] ?>" class="btn btn-dark">Read more</a>
                </div>
            </div>
        </article>
    <?php endforeach; ?>
</section>