<h1>Contact</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio vel exercitationem quasi, nemo voluptatem eligendi neque, repellendus unde iusto explicabo numquam voluptatum illum expedita ab quia, quibusdam doloribus dolorum. Nulla.</p>
<section id="contact">

    <?php if (isset($errors) && !empty($errors)) : ?>
        <?php foreach ($errors as $error) : ?>
            <div class="alert alert-danger" role="alert">
                <?= $error ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($isFinished) : ?>
        <div class="alert alert-success" role="alert">
                <p>Le compte <?=$email?> a été créé avec succès.</p>
                <p>Vous pouvez <a href="?page=login">vous connecter</a></p>
        </div>
    <?php else : ?>
    <form class="row g-3" action="?page=contact" method="POST">
        <div class="col-md-6">
            <label for="prenom" class="form-label">Prénom</label>
            <input type="text" class="form-control" id="prenom" name="prenom">
        </div>
        <div class="col-md-6">
            <label for="nom" class="form-label">Nom</label>
            <input type="text" class="form-control" id="nom" name="nom">
        </div>
        <div class="col-md-6">
            <label for="email" class="form-label">Email*</label>
            <input required type="email" class="form-control" id="email" name="email">
        </div>
        <div class="col-md-6">
            <label for="password" class="form-label">Password*</label>
            <input required type="password" class="form-control" id="password" name="password">
        </div>
        <div class="col-12">
            <div class="form-floating">
                <textarea rows="10" class="form-control" placeholder="Leave a message here" id="message" name="message"></textarea>
                <label for="message">Message</label>
            </div>
        </div>
        <div class="col-12">
            <div class="form-check">
                <input required class="form-check-input" type="checkbox" id="accepted" name="accepted">
                <label class="form-check-label" for="accepted">
                    I accept the privacy policy
                </label>
            </div>
        </div>
        <div class="col-12 mb-3">
            <button type="submit" class="btn btn-dark">Send</button>
        </div>
    </form>
    <?php endif; ?>    
</section>